[workflows/linux] Switch to self-hosted runners in Azure Kubernetes Service (#19183)
* [workflows/liux] Trying AKS runners

* Remove sudo usages

* Fix repositories path

* Well, adding debug output

* execution bit?

* more debug output

* using bash...

* We should use shell syntax for env variables in 'run' sections

* again, may be we should use bash...

* fix cloning path for openvino repo

* more debug output

* Trying to populate WORKSPACE var in other way

* Trying different WORKSPACE

* export ALL variables for samples tests

* Trying to put openvino build into correct directory

* Replace more occurences of BUILD_DIR...

* Use shell expansion instead of Actions syntax in run steps

* Skip unit test failures

* Oops, there's no pytest for MO unit tests

* Oops, typo

* Fix LAYER_TESTS_INSTALL_DIR variable expansion

* Fix LAYER_TESTS_INSTALL_DIR for new stages

* Replace all the varibles

* Comment out CCACHE_DIR

I want to test worst-case scenario

* Comment setup ccache step

* Revert "Comment out CCACHE_DIR"

This reverts commit 046663a9f1bd41c0869e7e66392fb57e65daea00.

* Just checking something

* Update with new stages from master

* One more stage to fix

* Fix INSTALL_DIR again (new stages were merged to master?)

* Remove concurrency limit (for test purposes)

* Trigger one more pipeline

* Disable concurrency settings

* Trigger another build

* Disable ccache (for testing purposes)

* trigger another build to measure duration without ccache

* And one more test commit

* Return back ccache

* Testing new image

* Enable concurrency back

* Using new image

* And another image

* Trying build on the clean image

* Install git

Upstream ubuntu image doesn't have git

* Oops, forgot apt-get update

* Upstream Ubuntu image, but using ACR cache

* Remove debug output

* Use Ubuntu image from ACR cache for the rest of the stages

* Display version of ccache

* Swith to ubuntu 20 temporarily (I hope)

* Set CCACHE_TEMP_DIR outside of shared space

* Revert "Swith to ubuntu 20 temporarily (I hope)"

This reverts commit 2e53109d83307e9b7f587d609d1e6e346ea6ed48.

* trying ccche nohardlink option

* Trying to disable ccache file cloning

* fix CCACHE_TEMPDIR

* Install git to Python unit tests stage

* Install libsnappy-dev as tests require it

* Install python to test stage

* Fix env vars syntax in few places

* Update docker image name

* Increase timeout for CPU tests

* Debug output - trying to find out what's wrong with test reports

* Change file name in debug-output 'find' command

* let's try shell syntax for upload artifact action...

It most likely won't work but I see strange output in the logs:
Error: No files were found with the provided path: /__w/openvino/openvino/install/tests/TEST*.xml
/runner/_work/openvino/openvino/install/tests/logs/failed/*.log
/runner/_work/openvino/openvino/install/tests/logs/crashed/*.log
/runner/_work/openvino/openvino/install/tests/logs/hanged/*.log
/runner/_work/openvino/openvino/install/tests/logs/interapted/*.log
/runner/_work/openvino/openvino/install/tests/logs/disabled_tests.log. No
artifacts will be uploaded.

So the first path is translated to the path inside the container
correctly and the rest are not O_o

* Revert "let's try shell syntax for upload artifact action..."

This reverts commit eb19b4f319838460a8c0729bf9946b493d76231b.

* Leave just disabled_tests.log (as it is the only one present)

* Use my own directory instead of github.workspace

Inside-container path translation doesn't work for upload-artifact
actions (it works only for the first path, but not for the rest)

* Revert "Leave just disabled_tests.log (as it is the only one present)"

This reverts commit 43218278809d6cef245c0c3c6f422f0893dbfa64.

* Okay, let's try hardcoded workspace path...

* Okay, path should be inside "official" workspace. Hardcode it

* Missed some variables, replace github.workspace to hard-coded value

* Remove debug output 'find' command

* Remove old-style cache setup

* Clean ccache stats after cmake

* Change docker image to the one with non-root user

* Oops, switch to Ubuntu 20

* Playing with concurrency group name

* Oops, forgot sudo for ninja installation

* Revert "Oops, forgot sudo for ninja installation"

This reverts commit a7e1730279e9c4309957e7b7922c01c992b4c3dc.

* Revert "Oops, switch to Ubuntu 20"

This reverts commit 19fe75f4afed6f177103d5feba6e67f5babdc695.

* Revert "Change docker image to the one with non-root user"

This reverts commit 553116492d7047c76d6951431675272284e3c2c7.

* Use Ubuntu 20 DockerHub image

* Trying to force apt-get packages not to wait for user input

* Make DEBIAN_FRONTED for all stages

* Update reason of skipped MO unit test

* Add DEBIAN_FRONTED to all jobs

* Fix environment variables expansion in newly-added stages

* Update .github/workflows/linux.yml

Co-authored-by: Ilya Lavrenov <ilya.lavrenov@intel.com>

* Update .github/workflows/linux.yml

Co-authored-by: Ilya Lavrenov <ilya.lavrenov@intel.com>

* Fix review comments

* More review comment fixes

* Remove DEBIAN_FRONTEND from Python Models job

* "Get tools versions" step is absent on master

---------

Co-authored-by: Ilya Lavrenov <ilya.lavrenov@intel.com>